name: Render Helm Charts

on:
  push:
    branches:
      - main  # You can adjust the branch here

jobs:
  render-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Read configuration file
        id: read-config
        run: echo "::set-output name=config::$(cat config.yaml)"

      - name: Parse YAML input
        id: parse-input
        run: |
          echo "${{ steps.read-config.outputs.config }}" > input.yaml
          echo "::set-output name=applications::$(yq r input.yaml 'applications')"

      - name: Iterate through applications
        id: iterate-apps
        run: |
          applications="${{ steps.parse-input.outputs.applications }}"
          for app in $(echo "${applications}" | yq r - -j | jq -r '.[].chartName'); do
            echo "${app}"
          done
          echo "::set-output name=apps::${applications}"

      - name: Render and Commit Helm Charts
        id: render-commit-charts
        run: |
          applications="${{ steps.iterate-apps.outputs.apps }}"
          for app in $(echo "${applications}" | yq r - -j | jq -c '.[]'); do
            chart_name=$(echo "${app}" | jq -r '.chartName')
            version=$(echo "${app}" | jq -r '.version')
            app_name="${chart_name}-${version}"
            mkdir -p "${app_name}"
            helm template "${chart_name}" ./path/to/helm/charts/${chart_name} --version "${version}" > "${app_name}/rendered.yaml"
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add "${app_name}"
            git commit -m "Add rendered Helm chart for ${app_name}"
          done
          git push
